global:
    scrape_interval: 20s
    scrape_timeout: 10s
scrape_configs:
    - job_name: "todo-list"
      metrics_path: "/metrics"
      static_configs:
          - targets: ["host.docker.internal:3999"]
      authorization:
          type: "Bearer"
          credentials: "my_token"
